### MODULE 3: INTRODUCTION TO NUMPY  ###


1. Importing a csv file using numpy

In [1]:
import numpy as np

In [2]:
firstarray=np.genfromtxt("./data/Numpydata.csv", delimiter=",")
print(firstarray)

[[  1.  10. 100.]
 [  2.  20. 100.]
 [  3.  30. 100.]
 [  4.  40. 100.]
 [  5.  50. 100.]
 [  6.  60. 100.]
 [  7.  70. 100.]
 [  8.  80. 100.]
 [  9.  90. 100.]
 [ 10. 100. 100.]]


2. Saving an array as a csv file using numpy

In [3]:
import numpy as np

nparray=([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(nparray)

#saving the array as a csv file(excel)
np.savetxt("./data/firstarray.csv", nparray, delimiter=",")
#reading the csv into an array
firstarray=np.genfromtxt("./data/firstarray.csv", delimiter=",")
print(firstarray)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]



3. Displaying the details of the array using numpy functions 

In [4]:
import numpy as np

arr=np.array([[1,2,3], [4,5,6]])

print("Array is of type: ", type(arr))

print("No. of dimensions: ", arr.ndim)

print("Shape of the array: ", arr.shape)

print("Size of the array: ", arr.size)

print("Array stores elements of type: ", arr.dtype)
#if the values in an array is float, the data type changes

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of the array:  (2, 3)
Size of the array:  6
Array stores elements of type:  int32


4. Numpy array functions (Creating, reshaping and flattening)


In [5]:

import numpy as np

#Creating an array from list with data type
a=np.array([[1,2,3],[4,5,6]], dtype='float')
print("Array created using passed list:\n", a)

Array created using passed list:
 [[1. 2. 3.]
 [4. 5. 6.]]


In [6]:
#Creating an array from tuples
b=np.array((1,2,3))
print("\nAn array created using passed tuple:\n", b)



An array created using passed tuple:
 [1 2 3]


In [7]:
#Creating a 3x4 array with all zeroes
c=np.zeros((3,4))
print("\nAn array initialized with all zeroes:\n", c)


An array initialized with all zeroes:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
#Creating a constant value array of complex type
d=np.full((3,3), 6, dtype='complex')
print("\nAn array initialized with all 6s:"
      "(Array type is complex)\n", d)


An array initialized with all 6s:(Array type is complex)
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [9]:
#Creating anarray with random values
e=np.random.random((2,2))
print("\nA random array:\n", e)


A random array:
 [[0.54904561 0.23953799]
 [0.85484423 0.25264294]]


In [10]:
#Creating a sequence of integers from 0 to 5 with steps of 30
f=np.arange(0,30,5)
print("\nA sequential array with steps of 5:\n", f)


A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [11]:
#Creating a sequence of 10 values in range 0 to 5
f=np.linspace(0,5,10)
print("\nA sequential array with steps of 5:\n", f)


A sequential array with steps of 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [12]:
#Reshaping a 3x4 array to 2x2x3 array
arr=np.array([[1,2,3,4],
              [4,5,6,7],
              [6,7,8,9,]])
newarr=arr.reshape(2,2,3)
print("\nOriginal Array:\n", arr)
print("\nReshaped Array:\n", newarr)


Original Array:
 [[1 2 3 4]
 [4 5 6 7]
 [6 7 8 9]]

Reshaped Array:
 [[[1 2 3]
  [4 4 5]]

 [[6 7 6]
  [7 8 9]]]


In [13]:
#Flattening an array
arr=np.array([[1,2,3],[4,5,6]])
flarr=arr.flatten()
print("\nOriginal Array:\n", arr)
print("\nFlattened Array:\n", flarr)


Original Array:
 [[1 2 3]
 [4 5 6]]

Flattened Array:
 [1 2 3 4 5 6]


5. Arithmetic operations on arrays using numpy functions  

In [14]:
import numpy as np

arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [15]:
#Adds 1 to each element in the array
print(arr+1)

[2 3 4 5]


In [16]:
#Subracts 3 from each element in the array
print(arr-3)

[-2 -1  0  1]


In [17]:
#Multiplies 10 to each element in the array
print(arr*10)

[10 20 30 40]


In [18]:
#Squaring each element in the array
print(arr**2)

[ 1  4  9 16]


In the above method, array is not updated after each print statement. Hence each operation
is performed on the original array.

In the following method, the array is updated after each operation is executed and the
further operations are performed on the updated array.

In [19]:
arr=np.array([1,2,3,4])

arr+=1
print(arr)


[2 3 4 5]


In [20]:
arr-=3
print(arr)

[-1  0  1  2]


In [21]:
arr*=10
print(arr)

[-10   0  10  20]


In [22]:
arr**=2
print(arr)

[100   0 100 400]


6. Printing the transpose of the array using numpy function

In [23]:

 #Transposing an array
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print("\nOriginal Array:\n", arr)
print("\nTranspose of the array:\n", arr.T)



Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of the array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


7. Slicing an array using numpy functions

In [24]:
import numpy as np
x=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(x[1:7:2])

[1 3 5]


In [25]:
print(x[-2:10])

[8 9]


In [26]:
print(x[5:])

[5 6 7 8 9]


8. Boolean indexing using numpy on arrays

In [27]:
import numpy as np
a=np.array([10, 40, 80, 50, 100])
print(a[a>50])


[ 80 100]


9. Sum functions on arrays using numpy

In [28]:
import numpy as np
b=np.array([[5,5],[4,5],[16,4]])

#Sum of the elements in the row
sumrow=b.sum(1)
print(sumrow)

[10  9 20]


In [29]:
#elements of the row whose sum is divisible by 10
print(b[sumrow%10==0])

[[ 5  5]
 [16  4]]
